import inro.emme.desktop.app as app

def main():
    print("Calculating supplemental trips generated by exterals, special generators, and group quarters.")
    print('Finished generating supplemental trips.')

if __name__ == "__main__":
    main()