################################### SKIMS AND PATHS ####################################
log_file_name = 'skims_log.txt'
STOP_THRESHOLD = 0.005
parallel_instances = 4   # Number of simultaneous parallel processes. Must be a factor of 4.
max_iter = 50             # Assignment Convergence Criteria
best_relative_gap = 0.01  # Assignment Convergence Criteria
relative_gap = 0.0001
normalized_gap = 0.01

MIN_EXTERNAL = 1511      #zone of externals 
MAX_EXTERNAL = 1528      #zone of externals 
HIGH_TAZ = 1359
LOW_PNR = 1360 #external dummy is also included
HIGH_PNR = 1510
EXTERNALS_DONT_GROW=[1511]
