#####################################
# Network Import Settings
####################################
master_project = 'LoadTripTables'
network_summary_project = 'Projects/LoadTripTables/LoadTripTables.emp'
tod_networks = ['am', 'md', 'pm', 'ni']
sound_cast_net_dict = {'6to9' = 'am', '9to1530' = 'md', '1530to1830' = 'pm', '1830to6' = 'ni'}
load_transit_tod = ['6to9', '9to1530', '1530to1830', '1830to6']
tods = ['6to9', '9to1530', '1530to1830', '1830to6']

mode_file = 'modes.txt'
transit_vehicle_file = 'vehicles.txt' 
base_net_name = '_roadway.in'
turns_name = '_turns.in'
transit_name = '_transit.in'
shape_name = '_linkshapes.in'
no_toll_modes = ['s', 'h']  
unit_of_length = 'mi'    # units of miles in Emme
coord_unit_length = 0.0001894    # network links measured in feet, converted to miles (1/5280)
headway_file = 'sc_headways.csv'
zone_partition_file = 'zone_partitions.txt'
transit_line_extra_attributes = ['@transittype']

[transit_tod]

[transit_tod.6to9]
4k_tp = "am"
num_of_hours = 3
[transit_tod.9to1530]
4k_tp = "md"
num_of_hours = 6.5
[transit_tod.1530to1830]
4k_tp = "pm"
num_of_hours = 3
[transit_tod.1830to6]
4k_tp = "ni"
num_of_hours = 11.5

[extra_attributes_dict]
"@tveh" = "total vehicles"
"@mveh" = "medium trucks"
"@hveh" = "heavy trucks"
"@dveh" = "delivery trucks"
"@vmt" = "vmt"
"@vht" = "vht"
"@trnv" = "buses in auto equivalents"
"@ovol" = "observed volume"
"@bveh" = "number of buses"

