

#################################
# NETWORK SUMMARY
#################################

network_results_path = 'outputs/network/network_results.csv'
iz_vol_path = 'outputs/network/iz_vol.csv'
transit_line_path = 'outputs/transit/transit_line_results.csv'
transit_node_path = 'outputs/transit/transit_node_results.csv'
transit_segment_path = 'outputs/transit/transit_segment_results.csv'
boardings_by_agency_path = 'outputs/transit/daily_boardings_by_agency.csv'
special_routes_path = 'outputs/transit/daily_boardings_special_routes.csv'
boardings_by_tod_agency_path = 'outputs/transit/boardings_by_tod_agency.csv'
boardings_by_stop_path = 'outputs/transit/boardings_by_stop.csv'
light_rail_boardings_path = 'outputs/transit/light_rail_boardings.csv'

[transit_extra_attributes_dict]
@board = "total boardings"
@timtr = "transit line time"

# Transit Line OD Table list 
[transit_line_dict]
6025 = 'Eastlink EB'
6026 = 'Eastlink WB'
6039 = 'ST3_to_issaquah_WB'
6040 = 'ST3_to_issaquah_EB'
7040 = 'ST560 NB'
7041 = 'ST560 SB'
4019 = 'B Line EB'
4020 = 'B Line WB'

[special_route_lookup]
6025 = 'Eastlink EB'
6026 = 'Eastlink WB'
6039 = 'ST3_to_issaquah_WB'
6040 = 'ST3_to_issaquah_EB'
7040 = 'ST560 NB'
7041 = 'ST560 SB'
4019 = 'B Line EB'
4020 = 'B Line WB'


[bkrlink_map]
1 = 'Bellevue'
2 = 'Kirkland'
3 = 'Redmond'
4 = 'BKR Fringe'
0 = 'Outside BKR'

uc_list = ['@svtl1', '@svtl2', '@svtl3', '@svnt1', '@svnt2', '@svnt3', '@h2tl1', '@h2tl2', '@h2tl3', '@h2nt1', '@h2nt2', '@h2nt3', '@h3tl1', '@h3tl2', '@h3tl3', '@h3nt1', '@h3nt2', '@h3nt3', '@mveh', '@hveh', '@bveh']

